server:
  port: 9090
# TODO Database Config
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db_cards_v1?enabledTLSProtocols=TLSv1.2
    username: emtech
    password: emtech@2022
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: db_cards_v1
    placeholder-replacement: false

  ## TODO EMAILS Config
  application:
    jwtExpirationMs: 600000000
    jwtRefreshExpirationMs: 1200000000
    jwtSecret: /buCOEjS/+H7ZwekxyLKLdDeegHUGEytjxuivosdrzjRG4g4E+kA3uXO5lvGBVsl2NwqsgiGUUI5bjgY/6WG/VSIIG+22b1Rvdb59BY0YRod6Dnjnp0REsPn//hshs6ucnOVCBRp0lbVb1kP+EDOM7W7N72/+t+R1d8JQ4pjisoJZI4e0MV3PlZtzXKI0SY2EQUtI

    # TODO: CORS
    client:
      origin: "*"